# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YahooWeatherSwift2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YahooWeatherSwift2
  pod 'Alamofire'
  pod 'ObjectMapper','2.2.2'
  pod 'PKHUD'
  pod 'RealmSwift','2.4.2'
  pod 'FileProvider'

  target 'YahooWeatherSwift2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YahooWeatherSwift2UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end


